POST http://localhost:3003/api/blogs/
Content-Type: application/json

{
  "title": "Blog 9",
  "author": "WE",
  "url": "www.testblog.com",
  "likes": 9
}

###

DELETE http://localhost:3003/api/blogs/645e436970cf0d3f6cdd7336
Content-Type: application/json