FROM node:18-bookworm-slim

EXPOSE 3000

WORKDIR /app

COPY ./package*.json .

RUN npm install && npm install -g serve

COPY . .

RUN npm run build

CMD ["serve", "-s", "-l", "3000", "build"]

# docker run -d -p 3000:3000 front